using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("HQSoft")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HQSoft")]
[assembly: AssemblyProduct("HQSoft")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("3f0bc1fd-0d3e-4a8e-8f3d-2a40cbdca267")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
